### ISSUE TITLE
Support `webdiff --version`

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#101]
I'm actually not sure which version I'm running myself right now, and it's not easy to find out.

**Comment by daytonb** [comment]
Here's an easy way to check if you installed it via pip: `pip freeze | grep webdiff`

**Comment by daytonb** [comment]
This got fixed didn't it? I just ran `webdiff --version` on my install and got `webdiff 0.12.1`.

**Comment by danvk** [comment]
Yep! Thanks for the ping.
