### ISSUE TITLE
Optimize page load time

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#104]
When I run `git webdiff`, it takes ~3 seconds to see diff content in my browser.

Almost none of that time is spent in the `app.py` script (it's ~0.1s). Much more is spent on the diff page itself. Main sources of slowness include:
1. Tons of JS files
2. Using built-in JSXTransformer
3. Issuing an XHR for the diff data

All of these could be fixed.

**Comment by danvk** [comment]
@NikolasOliveira @daytonb if either of you is feeling inspired, this would be a great task for the next release. The browser is recompiling the webdiff JavaScript on every page load. We should just do that once and distribute the built, minified bundle.

**Comment by NikolasOliveira** [comment]
@danvk I'm pretty busy until about mid June. But this does look like a nice feature to work on next.
We should also merge in #109 for the next release. That PR has been open a long while now.

Cheers,
Niko

**Comment by danvk** [comment]
@NikolasOliveira sounds good. I just merged that PR :)

**Comment by NikolasOliveira** [comment]
@danvk nice, problem solved! :)

**Comment by daytonb** [comment]
I don't know any javascript, so I don't know that I could tackle that task.

**Comment by danvk** [comment]
I'm going to close this. If anyone has found webdiff slow in the past five years, they can file a new issue.
