### ISSUE TITLE
Slider (above images) not showing in Firefox

### ISSUE THREAD

**Issue by xuv** [danvk/webdiff#108]
When diffing two images, the slider is not showing in Firefox.
Version tested: Mozilla Firefox 45.0.2

![firefox-slider-notshowing](https://cloud.githubusercontent.com/assets/192539/14757259/9341c682-08bf-11e6-8eaf-bf0bf270194c.jpg)

**Comment by xuv** [comment]
Btw, doing more tests, I realize that the positioning of the images is also wrong.
![webdiff-firefox](https://cloud.githubusercontent.com/assets/192539/14762719/bc5bd608-094f-11e6-985e-b3ffc4db63b3.jpg)
When I add a background color to the `.swipe input` CSS rule, then the slider becomes visible. Not sure why.

**Comment by danvk** [comment]
Just confirmed that this is fixed in Firefox with the latest webdiff release.
