### ISSUE TITLE
`git webdiff` only works for all files if run from top folder of repo

### ISSUE THREAD

**Issue by daytonb** [danvk/webdiff#115]
If I run `git webdiff` in a subfolder of my git repo, diffs of files in my current folder display properly while those from other folders have a "none" on the left side of the diff, and the file selector at the top of the webdiff interface indicates the file is an "add".

If I run `git webdiff` in the top folder of the git repo, then all diffs display properly comparing current state to the state in HEAD.

My setup:
- Fedora 25
- python 2.7.12
- webdiff 0.12.1
- git 2.9.3

**Comment by danvk** [comment]
Sounds like a bug. PRs welcome!

**Comment by daytonb** [comment]
The bug is actually in `git difftool --dir-diff`, but got fixed in the 2.11.1 release which just came out yesterday ironically. 

> Git v2.11.1 Release Notes
> =========================
> 
> Fixes since v2.11
> -----------------
> 
> ...
> 
> * "git difftool --dir-diff" had a minor regression when started from
>    a subdirectory, which has been fixed.
> 
> ...
> 
>  * Even though an fix was attempted in Git 2.9.3 days, but running
>    "git difftool --dir-diff" from a subdirectory never worked. This
>    has been fixed.

So I think our best two options are:
1. Don't worry about it and wait for the world to catch up to git 2.11.1
2. Check the git version number and warn the users on the console or in the web interface that they need to run `git webdiff` from the top level of their git repo.

**Comment by danvk** [comment]
Thanks for digging into this. I vote for option 1 :)
