### ISSUE TITLE
Request for Python 3 support

### ISSUE THREAD

**Issue by daytonb** [danvk/webdiff#116]
I love this tool, especially the image diff capabilities! I wish it had Python 3 support. I can install it with `python3 -m pip install webdiff`, but the code isn't Python 3 compatible.

**Comment by daytonb** [comment]
I do. I just would like to see it Python 3 compatible too. I hope to have some time soonish to look into making this Python 3 compatible is no one else does.

**Comment by danvk** [comment]
Yes, please do! Would happily accept a PR.

**Comment by michalskop** [comment]
Related to this: It is not possible to run simply `git webdiff` nor `webdiff` on a system with default Python 3 (Ubuntu 16.04 in my case)

Btw. - How do I use webdiff in such a case? (I have Python 2, but I do not know how to tell webdiff to use it)

**Comment by daytonb** [comment]
### Python 2

If you do have python2 on your system, though you can install it with the python2 pip tool and it will use python2. The best way to ensure which version of Python you've installed it on is by using pip as a module as follows:

```
$ python2 -m pip install webdiff
```

Install webdiff with the above command and when you run `webdiff` or `git webdiff` it will work.


### Python 3

Alternatively, if you apply the patches in my pull request you could install it for python3 but not with pip trying to install from pypi.org. If you have more questions feel free to ask them.

**Comment by daytonb** [comment]
As of release 0.13.0, webdiff supports Python3. You should be able to pip install it in Python2 or Python3.
