### ISSUE TITLE
Customize diff colors

### ISSUE THREAD

**Issue by karan173** [danvk/webdiff#120]
Is there a way to customize diff colors (green/red). I find the current used colors too "light" and would like them to be a bit darker.

**Comment by danvk** [comment]
They're currently hard-coded, but some sort of configuration file for
settings like this would be a great addition. Would happily accept a PR.

**Comment by daytonb** [comment]
I looked at this for a while today. I figured out how to set a value in the configuration file and pass it on into the style tag in the html templates, but I can't seem to get my values to take effect. They are overridden by the values in codediff.css. And if I delete the appropriate rule from codediff.css my values put into the html template *still* don't apply.
