### ISSUE TITLE
Optimise two column diff interface as per screen size. It should resize based on browser width.

### ISSUE THREAD

**Issue by msimar** [danvk/webdiff#121]

**Comment by daytonb** [comment]
Right now the table entries that show code can show up to 101 characters. That's what limits the width of the webdiff application in the browser window. We could easily change this to say 501 characters and it would resize to as wide as any browser window would likely every be. However, if we do this we can up with code that is so visually separated between the two file displays that you don't get a useful diff tool. This is much like when you look at websites like the [Bash Reference Manual](https://www.gnu.org/software/bash/manual/html_node/What-is-Bash_003f.html#What-is-Bash_003f) where the text spans the width of the browser no matter how wide, which becomes very difficult to read. I think it's better that we leave the width the way it is.

**Comment by danvk** [comment]
I like the way that [Reviewable](https://reviewable.io/) handles this:

![image](https://user-images.githubusercontent.com/98301/42460353-a0aca430-836b-11e8-9e4d-cfd699b02a65.png)

You can drag the little arrow in the top right to adjust the width of the diff. If you click "auto", it goes to the max width for the current browser window.

If we wanted to get extra-fancy, we could try to detect line length settings based on a `setup.cfg` or `eslint.json` file in the project that you're diffing.

**Comment by daytonb** [comment]
@danvk, is that something you are interested in working on? It sounds a bit beyond my javascript skill level.

**Comment by kbauer** [comment]
As feedback: I'm currently using a TamperMonkey script to insert a style tag

    <style>
        td.code {width: 1024ch}
    </style>

It works perfectly well and enables the full range of convenient browser features, notably adjusting the exact formatting of what is displayed by:

- Resizing the window
- Zooming in and out

I.e. desktop browsers already come with capabilities that make "the page is too wide" pretty much a non-issue, or at least an issue that has to be addressed anyway on many websites, notably including wikipedia:

![image](https://user-images.githubusercontent.com/7498468/218308260-ec15111c-b361-4d8b-b512-751fbab0ddeb.png)
