### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by TJonesy** [danvk/webdiff#124]
I called `git webdiff` from the terminal but it just exits silently.  Is it supposed to give me a url to open it in the browser or something?

**Comment by danvk** [comment]
What's the state of your git repo? Do you have any unstaged changes?

If `git diff` doesn't produce any output, then neither will `git webdiff`.

**Comment by daytonb** [comment]
Given the amount of time this issue has been open without a response I'm going to close this issue. If there is no difference (such as two files being the same or a git repo with no modifications) then this is the expected behavior.
