### ISSUE TITLE
UserWarning: The 'environ['werkzeug.server.shutdown']' function is deprecated

### ISSUE THREAD

**Issue by song-fangzhen** [danvk/webdiff#142]
When executing `git webdiff`, this **WARNING** shows:
```
python3.8/site-packages/webdiff/app.py:208: UserWarning: The 'environ['werkzeug.server.shutdown']' function is deprecated and will be removed in Werkzeug 2.1.
```

**Comment by song-fangzhen** [comment]
Here are some discussions on this **WARNING**: https://github.com/plotly/jupyter-dash/issues/63#issuecomment-902415690.

Hope it will get fixed soon or later.

**Comment by danvk** [comment]
@song-fangzhen Better late than never! webdiff 0.16.0 should fix this error. Would love confirmation if it works for you.
