### ISSUE TITLE
Strange hljs-keyword text inserted into diff

### ISSUE THREAD

**Issue by tavinathanson** [danvk/webdiff#76]
Lately, I've been seeing this `hljs-keyword` text inserted into my diffs:

![image](https://cloud.githubusercontent.com/assets/322932/5349807/9fad42c4-7f0a-11e4-95d4-6403edbc4e0d.png)

I haven't yet dug into it to see what might be causing it.

**Comment by danvk** [comment]
I'm going to close this out unless we can reproduce.

**Comment by tavinathanson** [comment]
Oops, I didn't do a very good job helping you track this down! That said, I don't think I've seen this issue in a long time. :+1:
