### ISSUE TITLE
Missing dependency during install

### ISSUE THREAD

**Issue by rfagen** [danvk/webdiff#84]
I ran 'pip install webdiff' per the directions, and it installed. 

However, when I attempted to run 'webdiff Makefile README.md', I got:

    Traceback (most recent call last):
      File "/usr/local/bin/webdiff", line 7, in <module>
        from webdiff.app import run
      File "/Library/Python/2.7/site-packages/webdiff/app.py", line 10, in <module>
        import requests
    ImportError: No module named requests

so I ran 'pip install requests' and then webdiff worked fine.

Is there something to add to the packaging to automatically go out and get requests as a dependency?

**Comment by danvk** [comment]
Thanks for the heads up -- I'll do a point release w/ the fix.

**Comment by danvk** [comment]
I pushed a `0.9.1` to PyPI with the `requests` dependency.

**Comment by rfagen** [comment]
I love open source software!

Thanks!

Rob

On Monday, February 23, 2015, Dan Vanderkam <notifications@github.com>
wrote:

> Closed #84 <https://github.com/danvk/webdiff/issues/84> via #85
> <https://github.com/danvk/webdiff/pull/85>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/danvk/webdiff/issues/84#event-240387152>.
>


-- 
Rob Fagen
rob.fagen@gmail.com
